# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "gometalinter-${version}";
  version = "20160919-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "fcf716dd0d97f9a141b825df4d12579e4e619327";

  goPackagePath = "github.com/alecthomas/gometalinter";

  src = fetchFromGitHub {
    inherit rev;
    owner = "alecthomas";
    repo = "gometalinter";
    sha256 = "1d1p7jvnil9jb2ypa0mpkzmjxdky5kvnqiv967v4xr9pycq6adz7";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
