# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/alecthomas/assert";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/assert";
      rev = "561411bbb7e98b005e520f4c0f491c2d23782048";
      sha256 = "1jlsrlbr6yxbmxpfjia8dp9nj32svm37637bhlx6w78bzrda47w7";
    };
  }
  {
    goPackagePath = "github.com/alecthomas/colour";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/colour";
      rev = "60882d9e27213e8552dcff6328914fe4c2b44bc9";
      sha256 = "0iq566534gbzkd16ixg7fk298wd766821vvs80838yifx9yml5vs";
    };
  }
  {
    goPackagePath = "github.com/alecthomas/repr";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/repr";
      rev = "d44565ca483f0ed23c2ac9cda62c966b116e77a3";
      sha256 = "1ldvmdvxjwp6x01ri3ij4h4qvw7ymxksc0lyvxq3366va0vj0vxs";
    };
  }
  {
    goPackagePath = "github.com/alecthomas/template";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/template";
      rev = "a0175ee3bccc567396460bf5acd36800cb10c49c";
      sha256 = "0qjgvvh26vk1cyfq9fadyhfgdj36f1iapbmr5xp6zqipldz8ffxj";
    };
  }
  {
    goPackagePath = "github.com/alecthomas/units";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/units";
      rev = "2efee857e7cfd4f3d0138cc3cbb1b4966962b93a";
      sha256 = "1j65b91qb9sbrml9cpabfrcf07wmgzzghrl7809hjjhrmbzri5bl";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "6d212800a42e8ab5c146b8ace3490ee17e5225f9";
      sha256 = "01i0n1s4j7khb7n6mz2wymniz37q0vbzkgfv7rbi6p9hpg227q93";
    };
  }
  {
    goPackagePath = "github.com/google/shlex";
    fetch = {
      type = "git";
      url = "https://github.com/google/shlex";
      rev = "6f45313302b9c56850fc17f99e40caebce98c716";
      sha256 = "0ybz1w3hndma8myq3pxan36533hy9f4w598hsv4hnj21l4br8jpx";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "66b8e73f3f5cda9f96b69efd03dd3d7fc4a5cdb8";
      sha256 = "17lf13ndnai9a6dlmykqkdyzf1z04q7kffs0l7kvd78wpv3l6rm5";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "792786c7400a136282c1664665ae0a8db921c6c2";
      sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
    };
  }
  {
    goPackagePath = "github.com/sergi/go-diff";
    fetch = {
      type = "git";
      url = "https://github.com/sergi/go-diff";
      rev = "ec7fdbb58eb3e300c8595ad5ac74a5aa50019cc7";
      sha256 = "1lpxhwqbypssj2vhlkj11fircllvxx4n985w6f76id5jany05h2w";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "976c720a22c8eb4eb6a0b4348ad85ad12491a506";
      sha256 = "0a2gxvqzacrj9k8h022zhr8fchhn9afc6a511m07j71dzw9g4y3m";
    };
  }
  {
    goPackagePath = "github.com/stretchrcom/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchrcom/testify";
      rev = "976c720a22c8eb4eb6a0b4348ad85ad12491a506";
      sha256 = "0a2gxvqzacrj9k8h022zhr8fchhn9afc6a511m07j71dzw9g4y3m";
    };
  }
  {
    goPackagePath = "gopkg.in/alecthomas/kingpin.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/alecthomas/kingpin.v2";
      rev = "e9044be3ab2a8e11d4e1f418d12f0790d57e8d70";
      sha256 = "1kzk1ylii9aqip0ss4zc2zxwa16lr5j3p3bgyjr276rig68i68ji";
    };
  }
]
