# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "lego-${version}";
  version = "20160926-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "ca0bd606b23a8b50f92915772917bd187ae1491b";

  goPackagePath = "github.com/xenolf/lego";

  src = fetchFromGitHub {
    inherit rev;
    owner = "xenolf";
    repo = "lego";
    sha256 = "0a6iqn1v5ass5baafakypjpszs8qmmfr82rg5jabff6nffjv3myn";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
