# This file was generated by go2nix.
[
  {
    goPackagePath = "cloud.google.com/go";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/gocloud";
      rev = "2c5922597efe4c81f0b98b588fb62573561286cc";
      sha256 = "1jv8wl3xyj8m1cc41mxcbcipyj6v41fnnl780dxffhpzfb4rfx71";
    };
  }
  {
    goPackagePath = "github.com/JamesClonk/vultr";
    fetch = {
      type = "git";
      url = "https://github.com/JamesClonk/vultr";
      rev = "e2c62e513c91feeb409764a8e6ab42e8ecc65df7";
      sha256 = "1impkrpw55nwrvlki6g28gv81zlfbarkwk7p0sy8s7xvnmx2883x";
    };
  }
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "682348d4ca74fa920a13b46a857bbde503dc3935";
      sha256 = "0pbgcaffzdgr0x0bysqwyd7cy5fyvpy3l5j9plrq50qrsz7h3czp";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "6d212800a42e8ab5c146b8ace3490ee17e5225f9";
      sha256 = "01i0n1s4j7khb7n6mz2wymniz37q0vbzkgfv7rbi6p9hpg227q93";
    };
  }
  {
    goPackagePath = "github.com/go-ini/ini";
    fetch = {
      type = "git";
      url = "https://github.com/go-ini/ini";
      rev = "6e4869b434bd001f6983749881c7ead3545887d8";
      sha256 = "1w7qcl0k7bsp6871vr8mbli09imd67qqq1vbvpll33d2vw12wmva";
    };
  }
  {
    goPackagePath = "github.com/jmespath/go-jmespath";
    fetch = {
      type = "git";
      url = "https://github.com/jmespath/go-jmespath";
      rev = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d";
      sha256 = "1kgzwiyqn24ba9kgpjxlq1h746gnyby0psbjj9mp2yx0h1i0kc4z";
    };
  }
  {
    goPackagePath = "github.com/jtolds/gls";
    fetch = {
      type = "git";
      url = "https://github.com/jtolds/gls";
      rev = "8ddce2a84170772b95dd5d576c48d517b22cac63";
      sha256 = "11rp9wbzkd71640rq0nwmgsddskx3qac8wzqz71ksdb7ixjj5fmj";
    };
  }
  {
    goPackagePath = "github.com/juju/ratelimit";
    fetch = {
      type = "git";
      url = "https://github.com/juju/ratelimit";
      rev = "77ed1c8a01217656d2080ad51981f6e99adaa177";
      sha256 = "1r7xdl3bpdzny4d05fpm229864ipghqwv5lplv5im5b4vhv9ryp7";
    };
  }
  {
    goPackagePath = "github.com/miekg/dns";
    fetch = {
      type = "git";
      url = "https://github.com/miekg/dns";
      rev = "db96a2b759cdef4f11a34506a42eb8d1290c598e";
      sha256 = "0h5n4psd0p7q55jadgsgz2a1aj791yanrfj76avalh6aawvdpcm6";
    };
  }
  {
    goPackagePath = "github.com/ovh/go-ovh";
    fetch = {
      type = "git";
      url = "https://github.com/ovh/go-ovh";
      rev = "d2b2eae2511fa5fcd0bdef9f1790ea3979fa35d4";
      sha256 = "1jj35rlzg0a7ggdw7skx3yc7y0vdxr3m8i181y8bdlp9asqwykjk";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "792786c7400a136282c1664665ae0a8db921c6c2";
      sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
    };
  }
  {
    goPackagePath = "github.com/smartystreets/assertions";
    fetch = {
      type = "git";
      url = "https://github.com/smartystreets/assertions";
      rev = "2063fd1cc7c975db70502811a34b06ad034ccdf2";
      sha256 = "1lzwy17q0vzmsqvdhbilbs31p84mczhmknfsaaysds4skhx27bqf";
    };
  }
  {
    goPackagePath = "github.com/smartystreets/goconvey";
    fetch = {
      type = "git";
      url = "https://github.com/smartystreets/goconvey";
      rev = "5db88ed452e937f2fd557de6f4f1af7f2eabed0b";
      sha256 = "1l7faj5gmc7hlrwybwv3ir4gwpw0phrdn8622pk64m6lig8lr7bw";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "976c720a22c8eb4eb6a0b4348ad85ad12491a506";
      sha256 = "0a2gxvqzacrj9k8h022zhr8fchhn9afc6a511m07j71dzw9g4y3m";
    };
  }
  {
    goPackagePath = "github.com/timewasted/linode";
    fetch = {
      type = "git";
      url = "https://github.com/timewasted/linode";
      rev = "37e84520dcf74488f67654f9c775b9752c232dc1";
      sha256 = "08gpys1c5xkh7f92fq31wb24vjksfnpbhfwini73dlvyi2w25a3c";
    };
  }
  {
    goPackagePath = "github.com/urfave/cli";
    fetch = {
      type = "git";
      url = "https://github.com/urfave/cli";
      rev = "d53eb991652b1d438abdd34ce4bfa3ef1539108e";
      sha256 = "0d02mmx79hrwd42wn0bchf28jqi47aj17pkfczq22gdxp6jd3r9w";
    };
  }
  {
    goPackagePath = "github.com/weppos/dnsimple-go";
    fetch = {
      type = "git";
      url = "https://github.com/weppos/dnsimple-go";
      rev = "65c1ca73cb19baf0f8b2b33219b7f57595a3ccb0";
      sha256 = "0rjj85ngfrl44wij35m333khb8fc5h26fz7hvrlxaxr7sk48rmn0";
    };
  }
  {
    goPackagePath = "github.com/xenolf/lego";
    fetch = {
      type = "git";
      url = "https://github.com/xenolf/lego";
      rev = "ca0bd606b23a8b50f92915772917bd187ae1491b";
      sha256 = "0a6iqn1v5ass5baafakypjpszs8qmmfr82rg5jabff6nffjv3myn";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "8e06e8ddd9629eb88639aba897641bff8031f1d3";
      sha256 = "0lpg958hxf5zljhrlyn073apb67rwjgqnmc3k039k2p8hvh1vzy4";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "f09c4662a0bd6bd8943ac7b4931e185df9471da4";
      sha256 = "17bfninkcsh1w28i8cd10943x20zpf8whkgwa1qzax5hbgbvfkrd";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "3c3a985cb79f52a3190fbc056984415ca6763d01";
      sha256 = "0c7x8wkya56z03j2qfm61932npsddgqyggi75hkla9755d1inqlv";
    };
  }
  {
    goPackagePath = "google.golang.org/api";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/google-api-go-client";
      rev = "adba394bac5800ff2e620d040e9401528f5b7615";
      sha256 = "1k43fpn76cjcpw7kb95hvfkgc3ssnaxf1h6jlfbbfls7ydl01shy";
    };
  }
  {
    goPackagePath = "gopkg.in/check.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/check.v1";
      rev = "4f90aeace3a26ad7021961c297b22c42160c7b25";
      sha256 = "0lc9dpdwy5vq6slli16m4883qrdxv35fyn4la4nj3hv2239jdsnv";
    };
  }
  {
    goPackagePath = "gopkg.in/ini.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/ini.v1";
      rev = "6e4869b434bd001f6983749881c7ead3545887d8";
      sha256 = "1w7qcl0k7bsp6871vr8mbli09imd67qqq1vbvpll33d2vw12wmva";
    };
  }
  {
    goPackagePath = "gopkg.in/square/go-jose.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/square/go-jose.v1";
      rev = "aa2e30fdd1fe9dd3394119af66451ae790d50e0d";
      sha256 = "0drajyadd6c4m5qv0jxcv748qczg8sgxz28nva1jn39f234m02is";
    };
  }
]
