# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/PuerkitoBio/goquery";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/goquery";
      rev = "152b1a2c8f5d0340f658bb656032a39b94e52958";
      sha256 = "0hl6mja3rl8xq263942sqjja2c5ypsd9p29ziprhisyad9nzq6aa";
    };
  }
  {
    goPackagePath = "github.com/andybalholm/cascadia";
    fetch = {
      type = "git";
      url = "https://github.com/andybalholm/cascadia";
      rev = "1c31af6f6c1a7b101ed05aacc7d8a738b43ae86e";
      sha256 = "161ij37wvd8mcr093cf3mrjp3wpm5j36yzksmgs73sz9m9pniq8v";
    };
  }
  {
    goPackagePath = "github.com/kovetskiy/godocs";
    fetch = {
      type = "git";
      url = "https://github.com/kovetskiy/godocs";
      rev = "2d9428f80f3442e07f67daf7ba378cd0ff6cfe24";
      sha256 = "128dlvxqk31crzl9p3ps0nir724cjzxv4lxpgdvsir0wvfp8f83j";
    };
  }
  {
    goPackagePath = "github.com/reconquest/executil-go";
    fetch = {
      type = "git";
      url = "https://github.com/reconquest/executil-go";
      rev = "e72bce509b1a5e89ab21f29c92830d4304620765";
      sha256 = "06z05hl4bym5agv0h1vgksj0mx0l4987ganwqcfb153w7pclvan3";
    };
  }
  {
    goPackagePath = "github.com/reconquest/hierr-go";
    fetch = {
      type = "git";
      url = "https://github.com/reconquest/hierr-go";
      rev = "bbf802f3f943e7b6a364a485ccf90807f3bfcc0e";
      sha256 = "1v3fssw881vcawc2abvp8abwb7705yzxrb0khbzmn8qvdpqwh7hl";
    };
  }
  {
    goPackagePath = "github.com/reconquest/ser-go";
    fetch = {
      type = "git";
      url = "https://github.com/reconquest/ser-go";
      rev = "47f084a1e4a5433ac3d6ab6cfe8c1e30028a4d76";
      sha256 = "1hgafiqc3mlazs2zg4rqjm4sasy2gjrjl64cy8mmlg5cayvbj4hq";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "8e06e8ddd9629eb88639aba897641bff8031f1d3";
      sha256 = "0lpg958hxf5zljhrlyn073apb67rwjgqnmc3k039k2p8hvh1vzy4";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "f09c4662a0bd6bd8943ac7b4931e185df9471da4";
      sha256 = "17bfninkcsh1w28i8cd10943x20zpf8whkgwa1qzax5hbgbvfkrd";
    };
  }
]
