# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "6d212800a42e8ab5c146b8ace3490ee17e5225f9";
      sha256 = "01i0n1s4j7khb7n6mz2wymniz37q0vbzkgfv7rbi6p9hpg227q93";
    };
  }
  {
    goPackagePath = "github.com/gdamore/encoding";
    fetch = {
      type = "git";
      url = "https://github.com/gdamore/encoding";
      rev = "b23993cbb6353f0e6aa98d0ee318a34728f628b9";
      sha256 = "0d7irqpx2fa9vkxgkhf04yiwazsm10fxh0yk86x5crflhph5fv8a";
    };
  }
  {
    goPackagePath = "github.com/go-errors/errors";
    fetch = {
      type = "git";
      url = "https://github.com/go-errors/errors";
      rev = "a41850380601eeb43f4350f7d17c6bbd8944aaf8";
      sha256 = "16r5pm0pvzl1qllybpd5fal510vi3fsfbwngwgir4gj904il1vbr";
    };
  }
  {
    goPackagePath = "github.com/jtolds/gls";
    fetch = {
      type = "git";
      url = "https://github.com/jtolds/gls";
      rev = "8ddce2a84170772b95dd5d576c48d517b22cac63";
      sha256 = "11rp9wbzkd71640rq0nwmgsddskx3qac8wzqz71ksdb7ixjj5fmj";
    };
  }
  {
    goPackagePath = "github.com/layeh/gopher-luar";
    fetch = {
      type = "git";
      url = "https://github.com/layeh/gopher-luar";
      rev = "921d03e21a7844141b02d4c729269b6709762f28";
      sha256 = "04k32fmp9rj9iq0nxwk8x6pszp85cbzrc0xkysywpl7v3w2k8aq7";
    };
  }
  {
    goPackagePath = "github.com/lucasb-eyer/go-colorful";
    fetch = {
      type = "git";
      url = "https://github.com/lucasb-eyer/go-colorful";
      rev = "9c2852a141bf4711e4276f8f119c90d0f20a556c";
      sha256 = "104b2p00sfrldvbvii5kz668mn035l5r35rrgdi4bd5fp5422n2j";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "66b8e73f3f5cda9f96b69efd03dd3d7fc4a5cdb8";
      sha256 = "17lf13ndnai9a6dlmykqkdyzf1z04q7kffs0l7kvd78wpv3l6rm5";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "d6bea18f789704b5f83375793155289da36a3c7f";
      sha256 = "1hnigpn7rjbwd1ircxkyx9hvi0xmxr32b2jdy2jzw6b3jmcnz1fs";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "756f7b183b7ab78acdbbee5c7f392838ed459dda";
      sha256 = "0yd3682x22lqrfq4h0q16c4swcfn3lmds05ijynm2fk1gcbnwiqn";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "792786c7400a136282c1664665ae0a8db921c6c2";
      sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
    };
  }
  {
    goPackagePath = "github.com/sergi/go-diff";
    fetch = {
      type = "git";
      url = "https://github.com/sergi/go-diff";
      rev = "ec7fdbb58eb3e300c8595ad5ac74a5aa50019cc7";
      sha256 = "1lpxhwqbypssj2vhlkj11fircllvxx4n985w6f76id5jany05h2w";
    };
  }
  {
    goPackagePath = "github.com/smartystreets/assertions";
    fetch = {
      type = "git";
      url = "https://github.com/smartystreets/assertions";
      rev = "2063fd1cc7c975db70502811a34b06ad034ccdf2";
      sha256 = "1lzwy17q0vzmsqvdhbilbs31p84mczhmknfsaaysds4skhx27bqf";
    };
  }
  {
    goPackagePath = "github.com/smartystreets/goconvey";
    fetch = {
      type = "git";
      url = "https://github.com/smartystreets/goconvey";
      rev = "5db88ed452e937f2fd557de6f4f1af7f2eabed0b";
      sha256 = "1l7faj5gmc7hlrwybwv3ir4gwpw0phrdn8622pk64m6lig8lr7bw";
    };
  }
  {
    goPackagePath = "github.com/stretchrcom/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchrcom/testify";
      rev = "976c720a22c8eb4eb6a0b4348ad85ad12491a506";
      sha256 = "0a2gxvqzacrj9k8h022zhr8fchhn9afc6a511m07j71dzw9g4y3m";
    };
  }
  {
    goPackagePath = "github.com/yosuke-furukawa/json5";
    fetch = {
      type = "git";
      url = "https://github.com/yosuke-furukawa/json5";
      rev = "07fdad7a3c55f2098b172ea58890470c07f7d392";
      sha256 = "1a0nhz829hlqrn6wh7rivvnq95ly0pcar0c96byjxbvz823nzy96";
    };
  }
  {
    goPackagePath = "github.com/yuin/gopher-lua";
    fetch = {
      type = "git";
      url = "https://github.com/yuin/gopher-lua";
      rev = "dd0fd531098d425ac1576765d9cca3274f8dd8d6";
      sha256 = "086p84kxkysis7gg4dayp7mbdgpj4lipsbn8v2s8dy9wmn0plyi8";
    };
  }
  {
    goPackagePath = "github.com/zyedidia/clipboard";
    fetch = {
      type = "git";
      url = "https://github.com/zyedidia/clipboard";
      rev = "72497670a7bd47eb648153f55bea83852546abe0";
      sha256 = "17pj4yzssqqh7lsbalbdycb2dp9x6wf58vj2rh4x3srirl8xfk00";
    };
  }
  {
    goPackagePath = "github.com/zyedidia/glob";
    fetch = {
      type = "git";
      url = "https://github.com/zyedidia/glob";
      rev = "7cf5a078d22fc41b27fbda73685c88a3f2c6fe28";
      sha256 = "0h86snzy50wvafh6i8ggw4zjmzwgrji33jvdzm4k0g7slbs48dx2";
    };
  }
  {
    goPackagePath = "github.com/zyedidia/tcell";
    fetch = {
      type = "git";
      url = "https://github.com/zyedidia/tcell";
      rev = "30195f90ef54b80935d79d8f1bd939429424168c";
      sha256 = "0fs3vsa8b05gkp20i4b640skzbcrr2d6aq2zkh57157wik1gh5lk";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "a7c023693a94aedd6b6df43ae7526bfe9d2b7d22";
      sha256 = "19kq5w431zrv1v4sd4ddzrafgz2dwcyrjzcdxp6yrzj2c3akpb71";
    };
  }
]
