# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
name = "goswagger-${version}";
  version = "20160925-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "8602d06bcde193b6f837e2e511f4403c8d3c5394";

  goPackagePath = "github.com/go-swagger/go-swagger";

  src = fetchFromGitHub {
    inherit rev;
    owner = "go-swagger";
    repo = "go-swagger";
    sha256 = "1bg85illfz4904fl080g4q8d8i3pjxx51mz6hjad2q4vln034ncx";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
